/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Soda-can.gltf --types 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    cylinder: THREE.Mesh
    cylinder_1: THREE.Mesh
    Tab: THREE.Mesh
  }
  materials: {}
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Soda-can.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.cylinder.geometry} material={nodes.cylinder.material} />
      <mesh geometry={nodes.cylinder_1.geometry} material={nodes.cylinder_1.material} />
      <mesh geometry={nodes.Tab.geometry} material={nodes.Tab.material} />
    </group>
  )
}

useGLTF.preload('/Soda-can.gltf')
